<?php return array (
  'site_title' => 'SMM Matrix',
  'time_zone' => 'Asia/Phnom_Penh',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'theme' => 'minimal',
  'fraction_number' => 2,
  'paginate' => 20,
  'email_verification' => 0,
  'email_notification' => 1,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'sender_email' => 'support@domain.com',
  'sender_email_name' => 'Bug Finder',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'domain.com',
    'smtp_port' => '465',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'support@domain.com',
    'smtp_password' => '9c09270f5448ad',
  ),
  'push_notification' => 0,
  'deposit_commission' => 1,
  'is_active_cron_notification' => 1,
  'error_log' => 0,
  'maintenance' => 0,
  'maintenance_message' => 'Sorry for the inconvenience.<br />Our website is currently undergoing scheduled maintenance.',
);